# Używamy obrazu builddependencies do budowy aplikacji
FROM builddependencies

# Skopiowanie wszystkich plików źródłowych do obrazu
COPY . /app

# Ustawienie katalogu roboczego
WORKDIR /app/redis

# Pobranie zależności i kompilacja aplikacji
RUN make distclean && make deps && make

# Ustawienie domyślnej komendy na zakończenie
CMD ["echo", "Application built successfully"]
